sonar.organization=manual-org-test-mass
sonar.projectKey=manual-org-test-mass_api-go-orders
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
